/*
    File: fn_initModule.sqf
    Author: Gruppe Adler (Original), BrianV1981 (Modifications)
    Date: 4/23/2025

    Description:
        Initializes the grad-persistence module on server and clients.
        Registers chat commands, handles JIP/disconnect, loads initial data based on config.

    MODIFICATION NOTES (Namespace Separation):
    - Added code block within the `if (isServer) then { ... };` section.
    - Purpose: To read the custom 'PersistenceCategories' class defined in CfgGradPersistence.
    - Action:
        - Iterates through each category defined under 'PersistenceCategories'.
        - Extracts the 'namespace' (string) and 'saveConfigRef' (string) for each category.
        - Stores this information in a global HashMap accessible via missionNamespace using
          the variable name generated by QGVAR(categoryConfigMap) (e.g., "grad_persistence_categoryConfigMap").
    - Result: This map allows other functions (save/load/wipe) to determine the correct
              profileNamespace to use for a specific data category (like "fortifications"),
              enabling the separation of persistent data.
    - Placement: This logic runs early in the server initialization, before any data loading
                 is triggered, ensuring the map is ready for use.
*/

#include "script_component.hpp"

// --- Chat command registration (no changes needed here) ---
["gradpersistenceSave", {
    [true, 10] remoteExec ["grad_persistence_fnc_saveMission",2,false];
}, "adminLogged"] call CBA_fnc_registerChatCommand;

["gradpersistenceLoad", {
    [] remoteExec ["grad_persistence_fnc_loadMission",2,false];
}, "adminLogged"] call CBA_fnc_registerChatCommand;

["gradpersistenceLoadPlayers", {
    [] remoteExec ["grad_persistence_fnc_loadAllPlayers",2,false];
}, "adminLogged"] call CBA_fnc_registerChatCommand;

["gradpersistenceLoadPlayer", {
    params [["_player",""]];
    if (_player == "") exitWith {
        systemChat "Use '#gradPersistenceLoadPlayer <name>' or '#gradPersistenceLoadPlayer <UID>'";
    };
    _this remoteExecCall ["grad_persistence_fnc_loadPlayerChatcommandServer",2,false];
}, "adminLogged"] call CBA_fnc_registerChatCommand;


// --- Server-Side Initialization ---
if (isServer) then {

    // --- Start: Added code for reading PersistenceCategories ---

    diag_log format ["%1: Initializing Persistence Category Map...", "grad_persistence"];

    // Initialize the global map to store category configurations.
    // The key will be the category name (e.g., "fortifications").
    // The value will be another HashMap containing "namespace" and "saveConfigRef".
    GVAR(categoryConfigMap) = createHashMap; // Example: grad_persistence_categoryConfigMap

    // Determine the root config path (use QGVAR if your CfgGradPersistence is named using it, otherwise use the plain string)
    // Assuming CfgGradPersistence is NOT using QGVAR for its class name based on original code usage elsewhere.
    private _configRootPath = missionConfigFile >> "CfgGradPersistence";
    private _categoriesConfig = _configRootPath >> "PersistenceCategories";

    if !(isClass _categoriesConfig) then {
        diag_log format ["%1: INFO - No 'PersistenceCategories' class found in %2. Namespace separation feature will not be active.", "grad_persistence", configName _configRootPath];
    } else {
        diag_log format ["%1: INFO - Reading 'PersistenceCategories' from %2.", "grad_persistence", configName _configRootPath];

        // Iterate through all defined categories (sub-classes) within PersistenceCategories
        private _categoryClasses = configProperties [_categoriesConfig, "isClass _x"];

        {
            private _categoryConfig = _x; // Config entry for the current category (e.g., ... >> "fortifications")
            private _categoryName = configName _categoryConfig; // Logical name, e.g., "fortifications"

            // Read the namespace string from the config
            private _namespace = getText (_categoryConfig >> "namespace");
            // Read the save flag reference string from the config
            private _saveConfigRef = getText (_categoryConfig >> "saveConfigRef");

            // Basic validation: Ensure both namespace and saveConfigRef are defined
            if (_namespace == "" || _saveConfigRef == "") then {
                diag_log format ["%1: WARNING - Category '%2' in PersistenceCategories is missing 'namespace' or 'saveConfigRef'. Skipping registration.", "grad_persistence", _categoryName];
            } else {
                // Store the data in our global map
                private _categoryData = createHashMap;
                _categoryData set ["namespace", _namespace];        // Store the namespace string
                _categoryData set ["saveConfigRef", _saveConfigRef]; // Store the name of the controlling save flag

                GVAR(categoryConfigMap) set [_categoryName, _categoryData];

                diag_log format ["%1: INFO - Registered category '%2': Namespace='%3', SaveFlagRef='%4'.", "grad_persistence", _categoryName, _namespace, _saveConfigRef];
            };

        } forEach _categoryClasses; // End loop through categories

        diag_log format ["%1: INFO - Finished reading PersistenceCategories. Map contents: %2", "grad_persistence", GVAR(categoryConfigMap)];
    };
    // Ensure the map is globally accessible (usually is with GVAR, but explicit doesn't hurt if unsure)
    missionNamespace setVariable [QGVAR(categoryConfigMap), GVAR(categoryConfigMap)];

    // --- End: Added code for reading PersistenceCategories ---


    // --- Original server-side initialization continues ---
    [] call grad_persistence_fnc_handleDisconnect;
    [] call grad_persistence_fnc_tagEditorObjects;

    // Read blacklist AFTER initializing category map
    private _blacklistFromConfig = [_configRootPath,"blacklist",[]] call BIS_fnc_returnConfigEntry;
    if (isNil QGVAR(blacklist)) then {GVAR(blacklist) = _blacklistFromConfig} else {GVAR(blacklist) append _blacklistFromConfig};
    GVAR(blacklist) = GVAR(blacklist) apply {toLower _x}; // Ensure blacklist is processed

    // Schedule mission loading if configured
    if ([_configRootPath, "loadOnMissionStart", 0] call BIS_fnc_returnConfigEntry == 1) then {
        _waitCondition = [_configRootPath, "missionWaitCondition", ""] call BIS_fnc_returnConfigEntry;
        if (_waitCondition == "") then {_waitCondition = "true"};
        // Schedule the main loading function AFTER map initialization
        [{call compile _this}, {[] call grad_persistence_fnc_loadMission}, _waitCondition] call CBA_fnc_waitUntilAndExecute;
    };

}; // End if (isServer)


// --- Client-Side Initialization (no changes needed here) ---
if (hasInterface) then {
    // Use _configRootPath defined above if needed, or redefine if scope requires
    private _configRootPathClient = missionConfigFile >> "CfgGradPersistence";
    if ([_configRootPathClient, "loadOnMissionStart", 0] call BIS_fnc_returnConfigEntry == 1) then {
        _waitCondition = [_configRootPathClient, "missionWaitCondition", ""] call BIS_fnc_returnConfigEntry;
        if (_waitCondition == "") then {_waitCondition = "true"};
        [{call compile _this}, {[] call grad_persistence_fnc_requestLoadPlayer}, _waitCondition] call CBA_fnc_waitUntilAndExecute;
    };
};


// --- Radio Mod Check (no changes needed here) ---
GVAR(acreLoaded) = isClass (configfile >> "CfgPatches" >> "acre_api");
GVAR(tfarLoaded) = isClass (configfile >> "CfgPatches" >> "tfar_core");