// A.I.M. Task Whitelist Override (Removed waitUntil to fix race condition)
// Omitted: Assassination, TransportInsertion, DestroyVehicles, DestroyInfantry, SabotageBuilding, InsurgencyDestroyAssets, Rescue, CSAR, MilDefence
ALIVE_autoGeneratedTasks = [
    "MilAssault",               
    "CivAssault",               
    "InsurgencyPatrol"          
];

diag_log "[A3M OPCOM] Custom staticData.sqf loaded. OPCOM restricted to MilAssault, CivAssault, and InsurgencyPatrol.";
