// Wait for ALiVE to initialize its core variables
waitUntil {!isNil "ALiVE_STATIC_DATA_LOADED"}; 

// A.I.M. Task Whitelist Override
// Omitted: Assassination, TransportInsertion, DestroyVehicles, DestroyInfantry, SabotageBuilding, InsurgencyDestroyAssets, Rescue, CSAR, MilDefence
ALIVE_autoGeneratedTasks = [
    "MilAssault",               
    "CivAssault",               
    "InsurgencyPatrol"          
];

diag_log "[A3M OPCOM] Custom staticData.sqf loaded. OPCOM restricted to MilAssault, CivAssault, and InsurgencyPatrol.";
