// A3M Speech Overhaul - Global Sound Arrays
A3M_Speech_West_Hit = [
    "A3M_speech_west_hit_wounded24", "A3M_speech_west_hit_wounded21", "A3M_speech_west_hit_wounded23", "A3M_speech_west_hit_wounded29", "A3M_speech_west_hit_wounded22", "A3M_speech_west_hit_wounded03", "A3M_speech_west_hit_wounded14", "A3M_speech_west_hit_friendlyFire15", "A3M_speech_west_hit_wounded01", "A3M_speech_west_hit_friendlyFire11", "A3M_speech_west_hit_friendlyFire05", "A3M_speech_west_hit_wounded06", "A3M_speech_west_hit_friendlyFire12", "A3M_speech_west_hit_wounded09", "A3M_speech_west_hit_friendlyFire02", "A3M_speech_west_hit_wounded13", "A3M_speech_west_hit_wounded28", "A3M_speech_west_hit_wounded25", "A3M_speech_west_hit_friendlyFire09", "A3M_speech_west_hit_wounded20", "A3M_speech_west_hit_friendlyFire13", "A3M_speech_west_hit_friendlyFire04", "A3M_speech_west_hit_wounded07", "A3M_speech_west_hit_wounded15", "A3M_speech_west_hit_friendlyFire03", "A3M_speech_west_hit_wounded16", "A3M_speech_west_hit_wounded19", "A3M_speech_west_hit_wounded05", "A3M_speech_west_hit_wounded04", "A3M_speech_west_hit_wounded26", "A3M_speech_west_hit_friendlyFire08", "A3M_speech_west_hit_wounded02", "A3M_speech_west_hit_wounded30", "A3M_speech_west_hit_wounded12", "A3M_speech_west_hit_wounded08", "A3M_speech_west_hit_friendlyFire14", "A3M_speech_west_hit_friendlyFire01", "A3M_speech_west_hit_friendlyFire10", "A3M_speech_west_hit_friendlyFire06", "A3M_speech_west_hit_wounded27", "A3M_speech_west_hit_friendlyFire07", "A3M_speech_west_hit_wounded18", "A3M_speech_west_hit_wounded10", "A3M_speech_west_hit_wounded11", "A3M_speech_west_hit_wounded17"
];
publicVariable "A3M_Speech_West_Hit";

A3M_Speech_West_Reload = [
    "A3M_speech_west_reload_reloading07", "A3M_speech_west_reload_reloading27", "A3M_speech_west_reload_reloading25", "A3M_speech_west_reload_reloading11", "A3M_speech_west_reload_reloading19", "A3M_speech_west_reload_reloading08", "A3M_speech_west_reload_reloading03", "A3M_speech_west_reload_ammoLow05", "A3M_speech_west_reload_ammoLow01", "A3M_speech_west_reload_reloading26", "A3M_speech_west_reload_reloading21", "A3M_speech_west_reload_reloading20", "A3M_speech_west_reload_reloading05", "A3M_speech_west_reload_reloading14", "A3M_speech_west_reload_reloading12", "A3M_speech_west_reload_reloading02", "A3M_speech_west_reload_reloading16", "A3M_speech_west_reload_reloading23", "A3M_speech_west_reload_reloading24", "A3M_speech_west_reload_reloading28", "A3M_speech_west_reload_reloading22", "A3M_speech_west_reload_ammoLow02", "A3M_speech_west_reload_reloading30", "A3M_speech_west_reload_reloading04", "A3M_speech_west_reload_reloading17", "A3M_speech_west_reload_ammoLow03", "A3M_speech_west_reload_ammoLow06", "A3M_speech_west_reload_reloading09", "A3M_speech_west_reload_reloading29", "A3M_speech_west_reload_reloading13", "A3M_speech_west_reload_reloading01", "A3M_speech_west_reload_reloading18", "A3M_speech_west_reload_reloading15", "A3M_speech_west_reload_reloading10", "A3M_speech_west_reload_ammoLow04", "A3M_speech_west_reload_reloading06", "A3M_speech_west_reload_reloading31"
];
publicVariable "A3M_Speech_West_Reload";

A3M_Speech_West_Callout = [
    "A3M_speech_west_callout_northwest03", "A3M_speech_west_callout_east01", "A3M_speech_west_callout_southeast04", "A3M_speech_west_callout_northeast02", "A3M_speech_west_callout_east02", "A3M_speech_west_callout_southeast01", "A3M_speech_west_callout_southwest01", "A3M_speech_west_callout_south02", "A3M_speech_west_callout_south01", "A3M_speech_west_callout_northeast01", "A3M_speech_west_callout_northwest02", "A3M_speech_west_callout_east05", "A3M_speech_west_callout_west03", "A3M_speech_west_callout_northwest04", "A3M_speech_west_callout_south04", "A3M_speech_west_callout_southwest02", "A3M_speech_west_callout_north04", "A3M_speech_west_callout_southeast02", "A3M_speech_west_callout_northeast04", "A3M_speech_west_callout_southwest04", "A3M_speech_west_callout_east03", "A3M_speech_west_callout_north01", "A3M_speech_west_callout_northwest06", "A3M_speech_west_callout_south06", "A3M_speech_west_callout_west01", "A3M_speech_west_callout_east04", "A3M_speech_west_callout_north03", "A3M_speech_west_callout_north02", "A3M_speech_west_callout_south03", "A3M_speech_west_callout_southeast05", "A3M_speech_west_callout_southeast03", "A3M_speech_west_callout_west05", "A3M_speech_west_callout_south05", "A3M_speech_west_callout_northwest05", "A3M_speech_west_callout_north05", "A3M_speech_west_callout_east06", "A3M_speech_west_callout_west04", "A3M_speech_west_callout_northeast06", "A3M_speech_west_callout_northeast03", "A3M_speech_west_callout_southeast06", "A3M_speech_west_callout_north06", "A3M_speech_west_callout_west06", "A3M_speech_west_callout_southwest05", "A3M_speech_west_callout_southwest06", "A3M_speech_west_callout_southwest03", "A3M_speech_west_callout_northeast05", "A3M_speech_west_callout_west02", "A3M_speech_west_callout_northwest01"
];
publicVariable "A3M_Speech_West_Callout";

A3M_Speech_West_Fired = [
    "A3M_speech_west_fired_frag03", "A3M_speech_west_fired_spotNade15", "A3M_speech_west_fired_spotNade17", "A3M_speech_west_fired_smoke05", "A3M_speech_west_fired_frag06", "A3M_speech_west_fired_spotNade05", "A3M_speech_west_fired_frag09", "A3M_speech_west_fired_incendiary01", "A3M_speech_west_fired_spotNade01", "A3M_speech_west_fired_incendiary02", "A3M_speech_west_fired_incendiary06", "A3M_speech_west_fired_explosive04", "A3M_speech_west_fired_explosive06", "A3M_speech_west_fired_explosive13", "A3M_speech_west_fired_frag08", "A3M_speech_west_fired_smoke04", "A3M_speech_west_fired_spotNade18", "A3M_speech_west_fired_smoke06", "A3M_speech_west_fired_frag01", "A3M_speech_west_fired_explosive03", "A3M_speech_west_fired_smoke01", "A3M_speech_west_fired_spotNade11", "A3M_speech_west_fired_explosive14", "A3M_speech_west_fired_incendiary07", "A3M_speech_west_fired_explosive01", "A3M_speech_west_fired_explosive08", "A3M_speech_west_fired_explosive11", "A3M_speech_west_fired_spotNade06", "A3M_speech_west_fired_explosive12", "A3M_speech_west_fired_frag11", "A3M_speech_west_fired_smoke09", "A3M_speech_west_fired_flash05", "A3M_speech_west_fired_frag07", "A3M_speech_west_fired_smoke02", "A3M_speech_west_fired_explosive05", "A3M_speech_west_fired_spotNade12", "A3M_speech_west_fired_flash06", "A3M_speech_west_fired_spotNade07", "A3M_speech_west_fired_flash03", "A3M_speech_west_fired_explosive02", "A3M_speech_west_fired_frag02", "A3M_speech_west_fired_frag13", "A3M_speech_west_fired_spotNade13", "A3M_speech_west_fired_explosive09", "A3M_speech_west_fired_spotNade08", "A3M_speech_west_fired_frag12", "A3M_speech_west_fired_explosive10", "A3M_speech_west_fired_incendiary05", "A3M_speech_west_fired_spotNade14", "A3M_speech_west_fired_smoke08", "A3M_speech_west_fired_flash02", "A3M_speech_west_fired_frag05", "A3M_speech_west_fired_flash01", "A3M_speech_west_fired_smoke07", "A3M_speech_west_fired_explosive07", "A3M_speech_west_fired_frag04", "A3M_speech_west_fired_spotNade04", "A3M_speech_west_fired_spotNade03", "A3M_speech_west_fired_incendiary03", "A3M_speech_west_fired_spotNade10", "A3M_speech_west_fired_flash04", "A3M_speech_west_fired_frag10", "A3M_speech_west_fired_flash07", "A3M_speech_west_fired_spotNade02", "A3M_speech_west_fired_frag14", "A3M_speech_west_fired_smoke03", "A3M_speech_west_fired_spotNade16", "A3M_speech_west_fired_spotNade20", "A3M_speech_west_fired_spotNade19", "A3M_speech_west_fired_spotNade09", "A3M_speech_west_fired_incendiary04"
];
publicVariable "A3M_Speech_West_Fired";

A3M_Speech_West_Cover = [
    "A3M_speech_west_cover_cover09", "A3M_speech_west_cover_cover04", "A3M_speech_west_cover_cover16", "A3M_speech_west_cover_cover03", "A3M_speech_west_cover_cover15", "A3M_speech_west_cover_cover02", "A3M_speech_west_cover_cover08", "A3M_speech_west_cover_cover05", "A3M_speech_west_cover_cover11", "A3M_speech_west_cover_cover18", "A3M_speech_west_cover_cover06", "A3M_speech_west_cover_cover07", "A3M_speech_west_cover_cover10", "A3M_speech_west_cover_cover17", "A3M_speech_west_cover_cover01", "A3M_speech_west_cover_cover13", "A3M_speech_west_cover_cover12", "A3M_speech_west_cover_cover14"
];
publicVariable "A3M_Speech_West_Cover";

A3M_Speech_West_Killed = [
    "A3M_speech_west_killed_allyDown14", "A3M_speech_west_killed_allyDown02", "A3M_speech_west_killed_allyDown06", "A3M_speech_west_killed_targDownHi13", "A3M_speech_west_killed_allyDown16", "A3M_speech_west_killed_allyDown21", "A3M_speech_west_killed_targDownLo02", "A3M_speech_west_killed_allyDown12", "A3M_speech_west_killed_targDownHi11", "A3M_speech_west_killed_targDownHi03", "A3M_speech_west_killed_allyDown09", "A3M_speech_west_killed_allyDown23", "A3M_speech_west_killed_targDownHi10", "A3M_speech_west_killed_allyDown05", "A3M_speech_west_killed_targDownLo05", "A3M_speech_west_killed_allyDown35", "A3M_speech_west_killed_allyDown28", "A3M_speech_west_killed_allyDown10", "A3M_speech_west_killed_targDownHi05", "A3M_speech_west_killed_targDownHi09", "A3M_speech_west_killed_allyDown19", "A3M_speech_west_killed_targDownLo06", "A3M_speech_west_killed_targDownLo01", "A3M_speech_west_killed_allyDown03", "A3M_speech_west_killed_targDownHi07", "A3M_speech_west_killed_allyDown31", "A3M_speech_west_killed_allyDown25", "A3M_speech_west_killed_allyDown33", "A3M_speech_west_killed_targDownHi02", "A3M_speech_west_killed_targDownHi04", "A3M_speech_west_killed_allyDown34", "A3M_speech_west_killed_allyDown27", "A3M_speech_west_killed_targDownLo07", "A3M_speech_west_killed_allyDown18", "A3M_speech_west_killed_allyDown20", "A3M_speech_west_killed_allyDown29", "A3M_speech_west_killed_targDownLo04", "A3M_speech_west_killed_targDownHi01", "A3M_speech_west_killed_targDownHi08", "A3M_speech_west_killed_allyDown15", "A3M_speech_west_killed_targDownHi06", "A3M_speech_west_killed_targDownHi12", "A3M_speech_west_killed_targDownLo09", "A3M_speech_west_killed_allyDown08", "A3M_speech_west_killed_allyDown17", "A3M_speech_west_killed_allyDown32", "A3M_speech_west_killed_allyDown07", "A3M_speech_west_killed_allyDown04", "A3M_speech_west_killed_targDownLo03", "A3M_speech_west_killed_allyDown24", "A3M_speech_west_killed_allyDown13", "A3M_speech_west_killed_targDownLo08", "A3M_speech_west_killed_targDownLo10", "A3M_speech_west_killed_allyDown30", "A3M_speech_west_killed_allyDown22", "A3M_speech_west_killed_allyDown11", "A3M_speech_west_killed_allyDown26", "A3M_speech_west_killed_allyDown01"
];
publicVariable "A3M_Speech_West_Killed";

A3M_Speech_West_Suppress = [
    "A3M_speech_west_suppress_suppressed21", "A3M_speech_west_suppress_suppressed09", "A3M_speech_west_suppress_rpg06", "A3M_speech_west_suppress_suppressed01", "A3M_speech_west_suppress_rpg07", "A3M_speech_west_suppress_suppressed05", "A3M_speech_west_suppress_suppressed31", "A3M_speech_west_suppress_suppressed30", "A3M_speech_west_suppress_suppressed07", "A3M_speech_west_suppress_suppressed24", "A3M_speech_west_suppress_suppressed28", "A3M_speech_west_suppress_suppressed11", "A3M_speech_west_suppress_suppressed16", "A3M_speech_west_suppress_suppressed06", "A3M_speech_west_suppress_rpg08", "A3M_speech_west_suppress_rpg01", "A3M_speech_west_suppress_suppressed20", "A3M_speech_west_suppress_rpg05", "A3M_speech_west_suppress_rpg09", "A3M_speech_west_suppress_suppressed23", "A3M_speech_west_suppress_suppressed19", "A3M_speech_west_suppress_suppressed13", "A3M_speech_west_suppress_suppressed17", "A3M_speech_west_suppress_rpg04", "A3M_speech_west_suppress_suppressed25", "A3M_speech_west_suppress_suppressed27", "A3M_speech_west_suppress_suppressed32", "A3M_speech_west_suppress_suppressed03", "A3M_speech_west_suppress_suppressed22", "A3M_speech_west_suppress_suppressed12", "A3M_speech_west_suppress_suppressed10", "A3M_speech_west_suppress_suppressed15", "A3M_speech_west_suppress_suppressed26", "A3M_speech_west_suppress_suppressed04", "A3M_speech_west_suppress_suppressed18", "A3M_speech_west_suppress_suppressed29", "A3M_speech_west_suppress_suppressed14", "A3M_speech_west_suppress_rpg02", "A3M_speech_west_suppress_suppressed02", "A3M_speech_west_suppress_rpg03", "A3M_speech_west_suppress_suppressed08"
];
publicVariable "A3M_Speech_West_Suppress";

